import React from "react";

const Home = () => {
  return (
    <div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
      <div>Hola mundo</div>
    </div>
  );
};

export default Home;
